development:
  adapter: postgresql
  encoding: unicode
  database: food_inventory_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: food_inventory_test
  pool: 5
  username:
  password:
